#默认的配置文件
configs={
    'db':{
        'host':'127.0.0.1',
        'port':3306,
        'user':'root',
        'password':'19950903a',
        'database':'awesome'
    },
    'session':{
        'secrept':'AwEsOme'
    }
}
